### PR TITLE
Quizki registration login Updated 181202

### PR DESCRIPTION
**Pull request by FrauDeborah**
Hi Johnathan (@haxwell),

I'm changing the PR comments, because I added the common-field-controls.service tests, and it didn't look like you had worked this PR yet. Sorry if I'm wrong!

1) I did some cleanup removing excess comments, and minor changes, then started working on the testing. The testing portion is not near complete, but I'm getting 25 successes for ng test at this time. Now I need to add the various detailed "it{}" tests. 

2) Question: What percentage of coverage levels are we targeting the tests? 100%, 80%, etc?

3) Should every little function/method have a test? For example, the common-field-controls.service.ts has the various functions/method for hidePassword. I wrote tests for each function. Yet, I'm not sure I did it correctly, because several functions are dependent upon each other. If any one of the functions fail, then multiple tests could fail. I'm not sure that should occur. Would you please review common-field-controls.service.spec.ts and advise your thoughts.

4) Also, I'm not sure about testing the login.component as it uses  MatDialogRef which is injected with the MAT_DIALOG_DATA. For the setup, I added a createSpyObj but haven't yet added the tests. I don't think it is correct to use createSpyObj. Can you advise what might be appropriate?

Thank you,

Happy Holidays!

Deborah

### CODE REVIEW

**Comment by haxwell** [comment]
Well, first, all the tests pass! So that's a good thing!

0) Try to submit PRs (and commits in general) that are all focused on one thing. No biggie, its just easier to understand how all the changes relate.

1) All of the removed code and comments appear like good changes. In a few cases, you added some commented out code.. No biggie, just something to be aware of.

2) If you can get 100%, do it. If not, then just get the major paths. It will take some time to get a feel for what the major paths are. Test as much as you can, I suppose.

3) In the `common-field-controls.service.spec.ts` test, your test cases look good.. I don't think you need the `comp` definition at the beginning of each test, however.. That's what `beforeEach()` is supposed to do: set up the component being tested before each test. Try replacing `comp` with `service`.

4) MAT_DIALOG_DATA... Ugh! Work is calling! I will have to get back to you on this one.. at first glance, it doesn't seem like anything is patently wrong, however.

**Comment by FrauDeborah** [comment]
Johnathan,

0.  Ok on the one thing concept. Should I start a new branch for each "one
thing" to offer up one thing in each PR?

1. Sorry, I likely commented out code to make a change. I tend to keep what
works, until I'm sure the change applied works. Will try to find the code
you meant and remove it.

2. Ok,  will replace comp with service and retest.

3. Ok.


Regards,

Deborah Frauenfelder

**Comment by haxwell** [comment]
0. Yes, a separate branch would be the way to handle it.

1. No worries... :)

4. Regarding your use of MAT_DIALOG_DATA... I don't see any issues here.. lets go with it until we run into a reason not to.

Sorry for the delay! Were there any other questions? I think we can merge this as soon as you're ready.

**Comment by FrauDeborah** [comment]
Johnathan,

Go ahead and merge the quizkiRegistrationLogin branch PR. Afterward I'll
update my local, and merge local dev into each of the other branches for
which I have open PRs. After I push the branches to my origin, it will be
easier for you to see the new changes were one topic per PR.

Oh yes, after your merge, I'll start branches off dev rather than branching
from the quizkiRegistrationLogin.

Hoping Kaya is doing well! Praying for her health.

Thank you,

Deborah Frauenfelder

**Comment by haxwell** [comment]
Indeed! Everything you described was spot on... Thank you for your well-wishes. Kaya is doing better, she is off her ventilator, and will hopefully lose the I.V. soon too. She is doing better.

**Pull request merged**
