### PR TITLE
Qrl api tests

### PR DESCRIPTION
**Pull request by FrauDeborah**
Johnathan ( @haxwell ),

This PR added tests for the api.service. I created the branch qrlApiTests off local quizkiRegistrationLogin.

The tests all passed (42 success, 0 failures), but truly I'm not sure the tests are correct in what they are testing. 

Merge if correct, or provide feedback if I need to take further action. Thank you in advance.

Happy Holidays,

Deborah

### CODE REVIEW

**Comment by FrauDeborah** [comment]
Johnathan ( @haxwell ),

It appears that I made the correction but forgot to send an update.
Apparently, I changed the two header tests to read as "should be defined"

**Comment by haxwell** [comment]
@FrauDeborah  ???

**Comment by FrauDeborah** [comment]
Sorry about the confusion. Some how the threads for #30 and #31 got crossed. Your comment for #30 was on #31. I copied the comment here for you to see the original comment.

“In src/app/_services/api.service.spec.ts:
> + httpClient = TestBed.get(HttpClient); + httpTestingController = TestBed.get(HttpTestingController); +    service = new ApiService(httpClient); + }); + + afterEach(() => { + // After every test, assert that there are no more pending requests. + httpTestingController.verify(); + }); + + it('#getHttpHeaders should return httpHeaders json object ', () => { + expect(service.getHttpHeaders()).toBeDefined(); + }); + + it('#getHttpHeadersWithBase64Authorization should return httpHeaders json object ', () => { + const paramUsername = "username";
The test checks whether the object is defined, but not that it is a "httpHeaders json object" as the test name indicates.. so, either the title should be changed to match the test, or the test should do what the title says (check for conditions which would indicate an "httpHeaders json object").

”

I changed both of the header test to read “... should be defined”.



Regards,

Deborah 


On Jan 6, 2019, at 12:27 AM, Johnathan James <notifications@github.com> wrote:

@FrauDeborah ???

**Comment by FrauDeborah** [comment]
Closing this qrlApiTests because it was rebased to devApiTests. I'll issue another PR for devApiTests

**Pull request closed without merging**
