### PR TITLE
2nd Try to update to Angular7

### PR DESCRIPTION
**Pull request by FrauDeborah**
Hi Johnathan (@haxwell )

I'm not sure what happened to the Angular 7 update but something went wrong (likely by me). It looked like the other PR was merged and closed. So I opened a second PR.

This morning, I merged upstream/dev to local, pushed to origin, merged local dev into my various local branches then pushed each to origin. When I looked dev dependencies were back at 6.2.x (rather than 7.x.x) and had some missing files. I did not discovered what happened or what I did wrong; although I tried. Decided it was easier to just re-upgrade to Angular7. So this PR is a new PR for the upgrade. 

Perhaps with your experience you can tell me what happened. For me it was just easier to rebuild to Angular 7. 

Please would you look at dev dependency packages, and if needed merge this PR to dev.  Let me know whatever you decide.

Thank you.

Deborah (@FrauDeborah )

### CODE REVIEW

**Comment by haxwell** [comment]
Just FYI, sorry for the delay, I will review this soon!

**Comment by haxwell** [comment]
Regarding your question on your `git` process, I can't say what happened there.. it seems like your commands were the correct ones, in the correct sequence, etc. 

One of my greatest debugging tools is (as you discovered) start over. ;)

**Comment by FrauDeborah** [comment]
Hi Johnathan,

Failure tells us much.  *ng test* succeeded on my HP Pavilion laptop. I did
not test on the new laptop, because both machines have Angular 7 installed.
The test may have failed because your global CLI needs to be updated to
Angular 7 to be able to run ng test on this PR..  I was wondering if
everyone had to update their global environment for us to move to Angular
7. The answer is yes. Good to know.

I recommend you *don't merge this PR* (unless you already have) until some
sprint planned date in the future. Say the workd, and I will create a new
issue for Angular 7 so we can track. Everyone may need to move to Angular 7
on the same sprint once the json.package and angular.json are updated for
Angular 7. Here is the link for upgrading: https://update.angular.io/   I
selected Advanced and used Materials.

O yes, although *ng test* is working, I just realized this morning that I'm
having compatibility issues for *ng lint*.  The dependencies on *codeanlyzer,
**tslint *and *typescript *versions are likely the issue. I have learned to
like *ng lint *so I want it working. This morning I've been playing around
with my local copy the Angular 7 branch and my global installs. I can't
seam to get the dependencies set right to successfully run *ng lint*. I'll
continue to to work on it.

Here are the test results on my HP Pavilion laptop which now has Angular
7.x, Node 10.x, and Typescript 3.x (prior to my experimenting this morning.
PS test still worked after working with dependencies to get lint working.).
[image: image.png]

Let me know if you have questions. Or if you want to see my updateAngular7
branch working we could use Google hangout.

Regards,

Deborah Frauenfelder

**Comment by FrauDeborah** [comment]
Johnathon,

Well looks like this PR  got merged. I just checked github. Are you sure
you wanted to do that?

I'm asking before I pull into my local.


Regards,

Deborah Frauenfelder

**Comment by haxwell** [comment]
I was mistaken about the unit tests.. I had not updated my npm
dependencies, and that was causing the error.

I deleted my comment, but I knew it was too late.. You'd probably already
been sent a copy..

 So, yes, this PR seemed good, tests were indeed passing and the front end
ran as expected. I merged it, and each user will have to update their local
dependencies after pulling it.

I will put a notice saying so in slack.

**Pull request merged**
