### PR TITLE
Quizki header

### PR DESCRIPTION
**Pull request by FrauDeborah**
@haxwell Johnathan, 

This is an inprogress PR please don't merge yet. I need to sync with upstream/dev before the PR is merged. 

I still need to add the angular service to handle the changing page title and to finish the routing. Yet, I was hoping we might be able to discuss a few topics before I finish, maybe even tonight.

1.  **LOGO**: The quizki logo looks bad with all the built-in materials.anglur color themes. We can 'mixin' themes, but I haven't experimented with the process. built-in color themes will work fastest later when it counts.

- The logo is way to large. We need a smaller logo.

- How  did you create the logo? 

- Can we create a new logo or modify the existing logo. A Scalable Vector Graphic logo would be best for all platforms.  

2. **Header**: The headers are created from toolbars. They can be headers or toolbars. The way they are handled for accessibility are different for headers and for toolbars.

3. **Schematics**: Material.angular.io has [three types of schematics](https://material.angular.io/guide/schematics) that I believe we should use. The first one we should use is the navigation schematic which included menus, side-slider menus, and toolbars (we can have multiple toolbars). I created a myPlayground app this weekend to experiment with the navigation schematic. I can show you the possibilities this evening at the sprint planning meeting. It appears the apps with the schematics load much faster, than our quizki-frontend does currently. 

Deborah

### CODE REVIEW

**Comment by haxwell** [comment]
Regarding the image size, we can use a tool like the GIMP to edit the image, or you can try using CSS.. See https://www.w3schools.com/css/css_rwd_images.asp .. that page may not be your complete answer, but it will show you beginning possibilities.

Of the schematics you mention, the Navigation schematic seems most relevant.

**Comment by FrauDeborah** [comment]
The following changes were committed on 8/2/18 (I hope):

**Added** licenses references and invite to DMPJ meetup
        modified:   README.md  

**Created** a separate app-routing modules per recommendation in the Angular6 documentation. Removed routing from app-module.
        new file:   src/app/app-routing.module.spec.ts  
        new file:   src/app/app-routing.module.ts

**Updated** app component and module to support addition of routing module and header service.
        modified:   src/app/app.component.html
        modified:   src/app/app.module.ts

**Added** header service with one function/method getPageTitle(). The function partially works as it will display the pageTitle, if the page has a path, which the header component does not. The header is on every page, so no need to route to the header. Currently a fixed string is returned by getPageTitle() and the actual statement to use is commented out. The issue is multi sided. 

1. Currently the ActivatedRoute is the header itself, rather than the page to display the pageTitle.
2. The initial ActivatedRoute is not bound to a path until after ngOnInit is processed, we likely need to use another l[ifecycle hook](https://angular.io/guide/lifecycle-hooks) such as ngOnChange. (which I have not checked yet.  To play with lifecycle hooks so see how and when they work, scroll down to the lifecyle-hooks page to the section titled Lifecycle examples, then click the live example link.
3.  In addition to lifecycle hooks, I think we need to use resolve. Routing with resolve displays the page after all data points are resolved. To read about resolve, enter 'resolve' in the search box at [angular.io](https://angular.io/docs)
4. Perhaps we need to use the header.service on the page component being loaded.

So my research continues, but these are the files changes or added
        new file:   src/app/header.service.spec.ts
        new file:   src/app/header.service.ts
        modified:   src/app/header/header.component.css
        modified:   src/app/header/header.component.html
        modified:   src/app/header/header.component.ts

**Created** a page-not-found component which was recommended in the Angular6 documentation and added it to the app-routing.module
        new file:   src/app/page-not-found/page-not-found.component.css
        new file:   src/app/page-not-found/page-not-found.component.html
        new file:   src/app/page-not-found/page-not-found.component.spec.ts
        new file:   src/app/page-not-found/page-not-found.component.ts

Also, before long, I recommend updating dependancies many of which are outdated. Run "npm outdated" to see the list.

Also note you can access [myPlay](https://github.com/fraudeborah/myplay) which is Deborah's Playground for experimenting and learning Angular6. myPlay will show you how quizki may look we added the full app navigation including the sidebar. I have not added the full app navigation to quizki-frontend yet. Why! I wanted to fix pageTitle first. 

Let me know if you have questions/comments.

Thank you 

Deborah

**Comment by FrauDeborah** [comment]
@haxwell Johnathan,

**Almost successful!** The navigation with sidebar, header displaying pageTitle, and home page work using Chrome, and Foxfire browsers. Below is a screen capture in Foxfire browser. 

image

**Unresolved error -- IE threw an exception.**:
IE browser threw an exception and does not display anything other than the Quizki title tab. It is hard to tell where the exception originated (i.e., my code or Angular functionality). I'll need to continue researching that piece. Or I can open another issue. Personally I recommend we open a separate issued for IE. Thoughts?

Below is a screen capture from IE. 
image


**Possible new functionality**
We can open an enhancement issue if we want the side-navigation to hide itself when screen is large enough to support side navigation and component display. Side-navigation currently responds automatically hiding menu, when screen real-estate is not available. The hide functionality was part on the navigation schematic.

**Work Summary:**
1.  Removed header component
2.  Added navigation component (which includes a header bar showing pageTitle). 
3.  Added navigation service which provides the pageTitle services. pageTitle is displayed using the innerHTML with out any `<scripts>` involved to bind to the DOM. The [Angular security guide](https://angular.io/guide/security) permits the practice of binding to DOM with innerHTML when `<scripts>` are not used. You might want to read the **Sanitization example** to insure that I understood properly.
4. Updated AppRouting to remove the header routing and to add the navigation routing. 
5. Added pages are all basically blank, awaiting content -- except for the Page Not Found page. The Page Not Found page is currently written to tell developers that they likely have a routing error. We will need to update that page before the first new release is produced. 
6. Added the following initial pages with menu items on the side navigation. The pages were needed  to verify the navigation services were working to add the pageTitle:
- Home
- Generate Exam
- Search For An Exam
- Create Question
- Create Exam

7. Finally, the original work on quziki-frontend is still in the files as comments. When we start working on those implementations, someone may want to potentially re-use that code as a starting point. The files with code commented out are: app.component.html and  app.routing.module. While the imports are still active in the app.module.ts. That way the functionality works if the comments are removed in the app.component.html file. Admittedly, I did not test that functionally, but it compiled last time I checked without errors. I didn't spend time testing the old code, because it will be changing when the new endpoints are added.

**Summary:** 
Here's a summary of the file changes. (a: added, d: deleted, m: modified)

    m:  src/app/app-routing.module.ts                       | 22 ++++++----
    m:  src/app/app.component.html                          |  6 +--
    m:  src/app/app.component.spec.ts                      |  4 +-
    m:  src/app/app.component.ts                              |  2 +-
    m:  src/app/app.module.ts                                    | 27 ++++++++----
    a:   .../create-exam-page.component.css              |  0
    a:  .../create-exam-page.component.html            |  3 ++
    a:  .../create-exam-page.component.spec.ts}        | 12 +++---
    a:  .../create-exam-page/create-exam-page.component.ts   | 15 +++++++
    a:  .../create-question-page.component.css          |  0
    a:   .../create-question-page.component.html      |  3 ++
    a:   .../create-question-page.component.spec.ts   | 25 +++++++++++
    a:   .../create-question-page.component.ts           | 15 +++++++
    a:   .../generate-exam-page.component.css          |  0
    a:   .../generate-exam-page.component.html        |  3 ++
    a:   .../generate-exam-page.component.spec.ts    | 25 +++++++++++
    a:   .../generate-exam-page.component.ts            | 15 +++++++
    d:  src/app/header.service.spec.ts                         | 15 -------
    d:   src/app/header.service.ts                                | 41 ------------------
    d:   src/app/header/header.component.css          | 17 --------
    d:   src/app/header/header.component.html       | 20 ---------
    d:   src/app/header/header.component.ts            | 21 ----------
    a:   src/app/navigation.service.spec.ts                  | 15 +++++++
    a:    src/app/navigation.service.ts                         | 22 ++++++++++
    a:    src/app/navigation/navigation.component.css             | 23 ++++++++++
    a:    src/app/navigation/navigation.component.html           | 49 ++++++++++++++++++++++
    a:    src/app/navigation/navigation.component.spec.ts        | 25 +++++++++++
    a:    src/app/navigation/navigation.component.ts                | 48 +++++++++++++++++++++
    m:   .../page-not-found/page-not-found.component.html   |  4 +-
    a:  .../search-for-an-exam-page.component.css                    |  0
    a:  .../search-for-an-exam-page.component.html                 |  3 ++
    a:  .../search-for-an-exam-page.component.spec.ts              | 25 +++++++++++
    a:  .../search-for-an-exam-page.component.ts                       | 15 +++++++

Wow! What an Angular6 learning experience.....

Deborah

**Comment by FrauDeborah** [comment]
@haxwell 

Whoops I neglected to add the project board issue numbers to the  PR. 

quizki-frontend issue [Create a Home page #5](https://github.com/team-quizki/quizki-frontend/issues/5)
quizki-frontend issue  [Create a Header Component #6](https://github.com/team-quizki/quizki-frontend/issues/6)

**Pull request merged**
